name: 'yeswiki-release-action'
description: 'Build script to package YesWiki extensions and themes.'
branding:
  icon: 'package'
  color: 'yellow'

inputs:
  extension-dir:
    description: 'Extension directory to test and package.'
    required: true
    default: /github/workspace
  extension-name:
    description: 'YesWiki extension name (eg: yeswiki-extension-publication)'
    required: false
    default: ${{ github.repository }}
  extension-version:
    description: 'YesWiki extension version (eg: 2020-06-12)'
    required: false
    default: ${{ github.ref }}

outputs:
  md5sum:
    description: 'Package integrity signature.'
  archive-name:
    description: 'Package name, with its version name.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - /package.sh
    - ${{ inputs.extension-dir }}
    - ${{ inputs.extension-name }}
    - ${{ inputs.extension-version }}
